site_name: daVinci Documentation
theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md

plugins:
  - search
  - mkdocs-jupyter
  - bibtex:
      bib_file: "docs/references.bib"


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences  # Supports code blocks

eextra_javascript:
  - docs/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/MathJax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML


